### ISSUE TITLE
Add Github contributor

### ISSUE THREAD

**Issue by mburns** [NOX73/chef-golang#58]
Hi, I'd like to help maintain this cookbook and merge pending PRs. I've started using this at work and would rather maintain my fixes in a canonical place and not maintain a fork.

@NOX73 thoughts?

- [x] Github collaborator
- [ ] Supermarket collaborator (?) to upload new releases

Cheers!

**Comment by NOX73** [comment]
Welcome )

**Comment by NOX73** [comment]
Will appreciate your help

**Comment by mburns** [comment]
Thanks @NOX73!
