### ISSUE TITLE
source_url not backwards compatible

### ISSUE THREAD

**Issue by MartinBohman** [NOX73/chef-golang#61]
This commit https://github.com/NOX73/chef-golang/commit/f3a80b5882da0c081c9abf5c418a6a00398e58ec is not backwards compatible with Chef 11.10. The following happens:
```
Fetching 'golang' from https://github.com/NOX73/chef-golang.git (at master)
STDERR: The following error occurred while reading the cookbook `golang':
Ridley::Errors::FromFileParserError: Could not parse `/tmp/d20161006-11381-rcpqw8/metadata.rb': undefined method `source_url' for #<Ridley::Chef::Cookbook::Metadata:0x007f8acd0f1798>
```

Issues on other repos regarding this:
https://github.com/chef/chef/issues/2937
https://github.com/agileorbit-cookbooks/java/issues/240

**Comment by MartinBohman** [comment]
I created a PR for this: https://github.com/NOX73/chef-golang/pull/62

**Comment by mburns** [comment]
Thanks @MartinBohman. We'll get this fix cut into a release this week.
